apiVersion: v2
appVersion: "8"
description: A Helm chart for Kubernetes
name: zwavejs
type: application
version: 0.6.0
dependencies:
- name: base
  version: 1.0.4
  repository: https://helm.seibert.family/