{{- if .Values.controller.enabled -}}
apiVersion: apps/v1
kind: {{ include "base.controller.kind" . }}
metadata:
  name: {{ include "zwavejs.fullname" . }}
  labels:
    {{- include "zwavejs.labels" . | nindent 4 }}
    {{- with .Values.controller.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.controller.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.controller.replicas }}
  replicas: {{ .Values.controller.replicas }}
  {{- end }}
  {{- if eq (include "base.controller.kind" . ) "StatefulSet" }}
  serviceName: {{ include "zwavejs.fullname" . }}-headless
  {{- end }}
  selector:
    matchLabels:
      {{- include "zwavejs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.controller.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "zwavejs.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "zwavejs.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- with .Values.ports.http }}
            {{- if .enabled }}
            - name: http
              containerPort: {{ .port }}
              protocol: {{ default "TCP" .protocol | quote }}
            {{- end }}
            {{- end }}
          env:
            - name: TZ
              value: {{ .Values.env.timezone | quote }}
          volumeMounts:
            {{- if eq (include "base.persistence.enabled" .) "true" }}
            - name: storage-volume
              mountPath: {{ .Values.persistentVolumeClaim.mountPath }}
            {{- end}}
          startupProbe:
            httpGet:
              path: /
              port: http
              httpHeaders:
                - name: Host
                  value: {{ .Values.global.fqdn | quote }}
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              httpHeaders:
                - name: Host
                  value: {{ .Values.global.fqdn | quote }}
              port: http
          readinessProbe:
            httpGet:
              path: /
              httpHeaders:
                - name: Host
                  value: {{ .Values.global.fqdn | quote }}
              port: http
          resources: {{ if not .Values.resources -}}{}{{- end }}
            {{- if .Values.resources }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
      volumes:
        {{- if eq (include "base.persistence.enabled" .) "true" }}
        - name: storage-volume
          persistentVolumeClaim:
            {{- if and .Values.persistentVolumeClaim.create (empty .Values.persistentVolumeClaim.existingPersistentVolumeClaim) }}
            claimName: {{ printf "%s-storage" (include "zwavejs.fullname" . ) }}
            {{- else }}
            claimName: {{ .Values.persistentVolumeClaim.existingPersistentVolumeClaim }}
            {{- end }}
        {{- end }}
      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
