---
{{- if and .Values.istio.enabled .Values.istio.gateway.create -}} 
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "zwavejs.fullname" . }}
spec:
  selector:
      istio: {{ .Values.istio.gateway.selector.istio }}
  servers:
  {{- range .Values.istio.gateway.servers }}
  - port:
      name: {{ .name }}
      number: {{ .number }}
      protocol: {{ .protocol }}
    tls:
      {{- if hasKey .tls "mode" }}
      mode: {{ .tls.mode }}
      {{- end }}
      {{- if hasKey .tls "credentialName" }}
      credentialName: {{ .tls.credentialName }}
      {{- end }}
      {{- if hasKey .tls "httpsRedirect" }}
      httpsRedirect: {{ .tls.httpsRedirect }}
      {{- end }}
    hosts:
    - {{ $.Values.global.fqdn }}
  {{- end }} 
{{- end }}