repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.11.0
    hooks:
      - id: helm-docs
        args:
          # Make the tool search for charts only under the `charts` directory
          - --chart-search-root=charts

          # The `./` makes it relative to the chart-search-root set above
          - --template-files=./_templates.gotmpl

          # Repeating the flag adds this to the list, now [./_templates.gotmpl, README.md.gotmpl]
          # A base filename makes it relative to each chart directory found
          - --template-files=README.md.gotmpl
          
          # Document our dependency values
          - --document-dependency-values
          
          # Sort values based on file order, not alphanumeric
          - --sort-values-order=file

          # Increase log level to try to figure out why it's marking as failed
          - --log-level=trace
