# Default values for bitwarden-secrets.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

organizationID: ""
secretName: ""
secretsMap:
  - secretID: ""
    keyName: ""