# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: paperless
type: application
description: An umbrella chart for Paperless-NGX.
version: 0.1.28
appVersion: "1.9.2"
maintainers:
  - email: aaron@awseibert.net
    name: Aaron Seibert
dependencies:
- name: base
  version: 1.0.4
  repository: file://../base
- name: redis
  version: 0.1.9
  condition: global.broker.redis.enabled
  repository: file://../redis
  alias: broker
- name: postgres
  version: 0.1.17
  repository: file://../postgres
  condition: global.database.postgres.enabled
  alias: database
- name: paperless-ngx
  version: 0.1.23
  repository: file://../paperless-ngx
  alias: webserver
  condition: webserver.enabled
