apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    app: postgres
data:
  POSTGRES_DB: {{ .Values.configMap.postgresDB }}
  POSTGRES_USER: {{ .Values.configMap.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.configMap.postgresPassword }}
