{{- $fullName := include "bitwarden-secrets.fullname" . -}}
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata: 
  name: {{ $fullName }}
  labels:
    {{- include "bitwarden-secrets.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  organizationId: {{ .Values.organizationID | quote }}
  secretName: {{ .Values.secretName | quote }}
  map:
    {{- range .Values.secretsMap }}
    - bwSecretId: {{ .secretID | quote }}
      secretKeyName: {{ .keyName | quote }}
    {{- end }}
  authToken:
    secretName: bw-auth-token
    secretKey: token