{{- define "base.bitwardensecret.tpl" -}}
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: {{ .Release.Name | print "%s-%s" .Chart.Name }}
spec:
  organizationId: ""
  secretName: {{ .Release.Name | print "%s-%s-vault" .Chart.Name }}
  authToken:
    secretName: "bw-auth-token"
    secretKey: "token"
  map: {}
{{- end -}}
{{- define "base.bitwardensecret" -}}
{{- include "base.util.merge" (append . "base.bitwardensecret.tpl") -}}
{{- end -}}
