{{ if .Values.vault.bitwarden.enabled }}
{{- include "base.bitwardensecret" (list . "httpbin.bitwardensecret") -}}
{{ end }}
{{- define "mosquitto.bitwardensecret" -}}
{{ with .Values.vault.bitwarden.secretsMap }}
spec:
  map:
  {{ range . }}
    - bwSecretId: {{ .bwSecretId }}
      secretKeyName: {{ .secretKeyName }}
{{ end }}
{{ end }}
{{- end -}}