apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    # Config file for Mosquitto
    #
    per_listener_settings true
    persistence false
    #persistence_file
    #persistence_location

    # =================================================================
    # Listeners
    # =================================================================
    listener 1883
    allow_anonymous true
    socket_domain ipv4
    protocol mqtt

    listener 9001
    socket_domain ipv4
    allow_anonymous true
    protocol websockets