{{- if .Values.ingress.enabled -}}
{{- $fullName := include "mosquitto.fullname" . -}}
{{- $monitorProto := include "sitemonitor.protocol" . -}}
{{- $fqdn := printf "%s.%s" .Values.global.subdomain .Values.global.domain -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.gethomepage.enabled }}
    gethomepage.dev/enabled: {{ .Values.ingress.gethomepage.enabled }}
    gethomepage.dev/description: {{ .Values.ingress.gethomepage.description }}
    gethomepage.dev/group: {{ .Values.ingress.gethomepage.group }}
    gethomepage.dev/name: {{ .Values.ingress.gethomepage.name }}
    {{- if .Values.ingress.gethomepage.siteMonitor.enabled }}
    gethomepage.dev/siteMonitor: "{{ $monitorProto }}://{{ $fqdn }}"
    {{- end }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ $fqdn }}
      secretName: "mosquitto-tls"
  {{- end }}
  rules:
    - host: {{ $fqdn }}
      http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ .backend.service.name }}
                  port: 
                    name: {{ .backend.service.port }}
          {{- end }}
{{- end }}
