{{- if .Values.certificate.create -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: homepage-cert
    namespace: {{ .Values.certificate.namespace }}
spec:
    secretName: homepage-cert
    duration: {{ .Values.certificate.duration }}
    renewBefore: {{ .Values.certificate.renewBefore }}
    privateKey:
        algorithm: RSA
        size: 2048
    usages:
        - server auth
        - client auth
    dnsNames: {{ .Values.global.fqdn }}
    issuerRef:
        name: {{ .Values.certificate.issuerRef.name }}
        kind: {{ .Values.certificate.issuerRef.kind }}
{{- end }}