apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" (include "homepage.fullname" .) }}
  labels:
    app.kubernetes.io/name: {{ include "homepage.fullname" . }}
    {{- include "homepage.labels" . | nindent 4 }}
  {{- with .Values.config.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}