name: ci
on:
  push:
    branches:
      - main
jobs:
  version:
    uses: AaronSeibert/ci-utils/.github/workflows/autoversion.yml@main
  helmdocs:
    needs: version
    uses: AaronSeibert/ci-utils/.github/workflows/helmdocs.yml@main
  commit-updates:
    runs-on: ubuntu-latest
    needs: [version, helmdocs]
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Switch to main branch
        run: |
          git checkout main
      - name: Retrieve Generated Files
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - name: Update Generated Files
        run: |
          cat artifacts/README.md > README.md
          cat artifacts/Chart.yaml > Chart.yaml
          cat artifacts/CHANGELOG.md > CHANGELOG.md
      - name: Commit Changes
        run: |
          git commit -am "ci: $GITHUB_WORKFLOW [skip ci]"
      - name: Tag changes
        run: |
          git tag -a ${{ needs.version.outputs.version }} -m "ci: tag version ${{ needs.version.outputs.version }} [skip-ci]"
      - name: Push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --follow-tags